; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Morpho.Rhino"
#define MyAppVersion "2.0.6"
#define MyAppPublisher "One Click LCA"
#define MyAppURL "https://github.com/AntonelloDN/Morpho"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{26EF38C5-E124-4B7A-9834-40336EE24F69}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userappdata}\Morpho\
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
DefaultGroupName={#MyAppName}
LicenseFile=..\..\LICENSE
OutputDir=..\..\installer
OutputBaseFilename=Morpho.Rhino.Installer
SetupIconFile=..\..\logo\logo_morpho.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\morpho\*"; DestDir: "{userappdata}\Grasshopper\UserObjects\morpho"; Flags: ignoreversion
Source: "..\lib\Morpho\*"; DestDir: "{userappdata}\Morpho"; Flags: ignoreversion
Source: "..\templates\grasshopper\*"; DestDir: "{userappdata}\Morpho\grasshopper\templates"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

